#!/usr/bin/env bash
rm -rf dist
mkdir -p dist

echo "build src/styl/index.styl -> dist/bootstrap.css ..."
npx stylus -p src/styl/index.styl > dist/index.css
echo "minifying bootstrap.css ..."
npx uglifycss dist/index.css > dist/index.min.css

echo "build src/pug/index.pug to dist/index.pug ..."
npx tt src/pug/index.pug -o dist/index.pug

echo "deploy into local web ..."
rm -rf web/static/assets/lib/@loadingio/bootstrap.ext/dev/
mkdir -p web/static/assets/lib/@loadingio/bootstrap.ext/dev/
cp -R dist/* web/static/assets/lib/@loadingio/bootstrap.ext/dev/

echo "done."

